//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PcPartHelpenator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Case
    {
        public int Id { get; set; }
        public string CASEName { get; set; }
        public string CASESize { get; set; }
        public string CASELooks { get; set; }
        public int CASEPrice { get; set; }
        public int CASERating { get; set; }
        public string CASEImage { get; set; }
    }
}
