//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PcPartHelpenator
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPU
    {
        public int Id { get; set; }
        public string CPUName { get; set; }
        public string CPUSocketType { get; set; }
        public string CPUHeatsink { get; set; }
        public int CPUWatts { get; set; }
        public int CPUPrice { get; set; }
        public int CPURating { get; set; }
    }
}
