//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PcPartHelpenator
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPU
    {
        public int Id { get; set; }
        public string GPUName { get; set; }
        public string GPUBrand { get; set; }
        public int GPUWatts { get; set; }
        public int GPUPrice { get; set; }
        public int GPURating { get; set; }
    }
}
