//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PcPartHelpenator
{
    using System;
    using System.Collections.Generic;
    
    public partial class HEATSINK
    {
        public int Id { get; set; }
        public string HEATSINKName { get; set; }
        public string HEATSINKSocket { get; set; }
        public int HEATSINKPrice { get; set; }
        public int HEATSINKRating { get; set; }
    }
}
