//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PcPartHelpenator
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PcHelpenatorEntities : DbContext
    {
        public PcHelpenatorEntities()
            : base("name=PcHelpenatorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Case> Cases { get; set; }
        public virtual DbSet<CPU> CPUs { get; set; }
        public virtual DbSet<GPU> GPUs { get; set; }
        public virtual DbSet<HEATSINK> HEATSINKs { get; set; }
        public virtual DbSet<MOTHERBOARD> MOTHERBOARDs { get; set; }
        public virtual DbSet<OPTIONAL> OPTIONALs { get; set; }
        public virtual DbSet<POWERSUPPLy> POWERSUPPLies { get; set; }
        public virtual DbSet<RAM> RAMs { get; set; }
        public virtual DbSet<STORAGE> STORAGEs { get; set; }
    }
}
