//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PcPartHelpenator
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOTHERBOARD
    {
        public int Id { get; set; }
        public string MOTHERBOARDName { get; set; }
        public string MOTHERBOARDSize { get; set; }
        public string MOTHERBOARDSocke { get; set; }
        public string MOTHERBOARDRam { get; set; }
        public int MOTHERBOARDMaxRam { get; set; }
        public int MOTHERBOARDPrice { get; set; }
        public int MOTHERBOARDRating { get; set; }
    }
}
