//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PcPartHelpenator
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPTIONAL
    {
        public int Id { get; set; }
        public string OPTIONALType { get; set; }
        public string Property1 { get; set; }
        public int OPTIONALPrice { get; set; }
        public int OPTIONALRating { get; set; }
    }
}
