//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PcPartHelpenator
{
    using System;
    using System.Collections.Generic;
    
    public partial class POWERSUPPLy
    {
        public int Id { get; set; }
        public int POWERSUPPLYWatts { get; set; }
        public string POWERSUPPLYBrand { get; set; }
        public int POWERSUPPLYPrice { get; set; }
        public int POWERSUPPLYRating { get; set; }
    }
}
