//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PcPartHelpenator
{
    using System;
    using System.Collections.Generic;
    
    public partial class RAM
    {
        public int Id { get; set; }
        public string RAMType { get; set; }
        public string RAMSpeed { get; set; }
        public int RAMSize { get; set; }
        public int RAMPrice { get; set; }
        public int RAMRating { get; set; }
    }
}
