//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PcPartHelpenator
{
    using System;
    using System.Collections.Generic;
    
    public partial class STORAGE
    {
        public int Id { get; set; }
        public string STORAGEType { get; set; }
        public string STORAGESize { get; set; }
        public int STORAGEPrice { get; set; }
        public int STORAGERating { get; set; }
    }
}
